---
name: xndiff
version: 0.4
author:
  - http://code.google.com/p/xndiff
abstract: find differences between two nmap network scans
license: bsd
requires:
  Nmap::Parser: 0
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
resources:
  license: ~
